### ISSUE TITLE
Niente notifica di aggiunta eventi

### ISSUE THREAD

**Issue by MarcelloBavaroff** [bebora/polimi-schedule-js#3]
Ciao, volevo farvi i complimenti per il tool per importare il calendario delle lezioni su calendar. 
Un consiglio però, nel mio caso dopo aver fatto import non mi è apparso nessun feedback di conferma e quindi ho premuto più volte ritrovandomi poi con gli eventi x7 😅.
Come browser uso edge basato su chromium, non so se c'è qualche altra informazione che può tornarvi utile.

**Comment by bebora** [comment]
Hai ragione, ora c'è solo un feedback se viene creato un calendario nuovo. Vedo cosa ci posso fare.
