### ISSUE TITLE
Problema importazione calendario Google Calendar

### ISSUE THREAD

**Issue by lucadiste** [bebora/polimi-schedule-js#9]
Una volta generato il calendario (.ics) e importandolo direttamente dal sito su Calendar mi esce questo errore:
'Ops! Qualcosa è andato storto
Il testo che hai incollato non è valido oppure è in un nuovo formato non supportato.
Se stai usando Google Calendar, controlla di avere una connessione funzionante e di aver dato i permessi all'applicazione.
Il problema potrebbe capitare anche ad altri utenti! Puoi segnalarlo su Telegram o GitHub.'

<details>
    <summary>Debug info</summary>

User agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:104.0) Gecko/20100101 Firefox/104.0`
Timetable input:
```
055619 - FONDAMENTI DI CHIMICA E CHIMICA ORGANICA (Docente: D'Arrigo Paola )
Inizio lezioni: 12/09/2022 Fine lezioni: 23/12/2022
Lunedì dalle 14:15 alle 18:15, laboratorio sperimentale in aula DIP (-)
Lunedì dalle 09:15 alle 12:15, lezione in aula B8 1.3 (Milano Bovisa - Via Durando - Edificio B8 - Piano Terra Soppalco)
Martedì dalle 14:15 alle 16:15, lezione in aula L.07 (Milano Bovisa - Via La Masa - Edificio B12 - Piano Terra)
Venerdì dalle 09:15 alle 12:15, esercitazione in aula B8 0.5 (Milano Bovisa - Via Durando - Edificio B8 - Piano Terra)
Venerdì dalle 14:15 alle 17:15, lezione in aula B8 1.3 (Milano Bovisa - Via Durando - Edificio B8 - Piano Terra Soppalco)
Aula virtuale - D'Arrigo Paola
Aula virtuale - Scotti Massimo

083118 - MECCANICA DEI CONTINUI E DELLE STRUTTURE (PER ING. BIOMEDICA) (Docente: Rodriguez Matas Jose Felix )
Inizio lezioni: 15/09/2022 Fine lezioni: 23/12/2022
Giovedì dalle 10:15 alle 12:15, lezione in aula ROGERS (Milano Città Studi - Via Bonardi - Edificio 11 - Piano Terra)
Giovedì dalle 13:15 alle 15:15, esercitazione in aula 26.12 (Milano Città Studi - Via Golgi 20 - Edificio 26 - Piano Primo)
Venerdì dalle 10:15 alle 12:15, lezione in aula 25.S.1 (Milano Città Studi - Via Golgi 40 - Edificio 25 - Piano Seminterrato)
Venerdì dalle 12:15 alle 13:15, esercitazione in aula 25.S.1 (Milano Città Studi - Via Golgi 40 - Edificio 25 - Piano Seminterrato)
Aula virtuale - Rodriguez Matas Jose Felix

097534 - MECCANICA APPLICATA ALLE MACCHINE (Docente: Schito Paolo )
Inizio lezioni: 12/09/2022 Fine lezioni: 19/12/2022
Lunedì dalle 15:15 alle 17:15, esercitazione in aula 2.1.5 (Milano Città Studi - Piazza Leonardo da Vinci 32 - Edificio 2 - Piano Primo)
Lunedì dalle 10:15 alle 12:15, lezione in aula 25.S.2 (Milano Città Studi - Via Golgi 40 - Edificio 25 - Piano Seminterrato)
Aula virtuale - Schito Paolo
```
Error info: `"{\n  \"error\": {\n    \"code\": 403,\n    \"message\": \"Request had insufficient authentication scopes.\",\n    \"errors\": [\n      {\n        \"message\": \"Insufficient Permission\",\n        \"domain\": \"global\",\n        \"reason\": \"insufficientPermissions\"\n      }\n    ],\n    \"status\": \"PERMISSION_DENIED\",\n    \"details\": [\n      {\n        \"@type\": \"type.googleapis.com/google.rpc.ErrorInfo\",\n        \"reason\": \"ACCESS_TOKEN_SCOPE_INSUFFICIENT\",\n        \"domain\": \"googleapis.com\",\n        \"metadata\": {\n          \"service\": \"calendar-json.googleapis.com\",\n          \"method\": \"calendar.v3.Calendars.Insert\"\n        }\n      }\n    ]\n  }\n}\n"`
</details>

**Comment by bebora** [comment]
Resolved by removing the app from the user's Google [permissions page](https://myaccount.google.com/permissions) and giving permissions to the app again. Might be solved for other users in commit 03759477ed8552ae292f5ee5695868174df8ad11.
